- name: Copy local test.txt
  ansible.builtin.copy:
    src: test.txt
    dest: /var/www/html/test.txt
    owner: root
    group: root
    mode: '0644'
  when: "'linux' in group_names"
  become: true
  become_user: root 

- name: Copy local test.txt
  ansible.builtin.copy:
    src: default.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  when: "'linux' in group_names"
  become: true
  become_user: root 
