- name: Copy local test.txt
  ansible.builtin.copy:
    src: test.txt
    dest: "{{ root_folder }}/test.txt"
    owner: root
    group: root
    mode: '0644'
  when: "'linux' in group_names"
  become: true
  become_user: root 

- name: Copy local default.html
  ansible.builtin.copy:
    src: default.html
    dest: "{{ root_folder }}/index.html"
    owner: root
    group: root
    mode: '0644'
  when: "'linux' in group_names"
  become: true
  become_user: root 
