- name: Copy local test.txt
  ansible.windows.win_copy:
    src: test.txt
    dest: C:\inetpub\wwwroot\test-site\test.txt
  become_method: runas
  when: "'win' in group_names"

- name: Copy local default.html
  ansible.windows.win_copy:
    src: default.html
    dest: C:\inetpub\wwwroot\test-site\index.html
  become_method: runas
  when: "'win' in group_names"


  