ansible_host: 192.168.88.116
ansible_user: ansible
ansible_password: qwer*999
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore

############################

SITEDIR: C:\inetpub\wwwroot\test-site