---
- name: Install IIS on Windows Server
  hosts: win
  become_method: runas
  tasks:
    - name: Install IIS on Windows
      win_feature:
        name: Web-Server
        state: present
        include_management_tools: yes
  