---
- name: Create test website,folder and copy files
  hosts: win
  become_method: runas
  tasks:
    - name: Create a new application pool in 'Started' state
      community.windows.win_iis_webapppool:
        name: test-pool
        state: started

    - name: Create directory structure
      ansible.windows.win_file:
        path: C:\inetpub\wwwroot\test-site
        state: directory

    - name: Turn off default site
      win_iis_website:
        name: "Default Web Site"
        state: stopped

    - name: Create test website on IIS
      win_iis_website:
        name: "test-site"
        state: started
        application_pool: test-pool
        physical_path: C:\inetpub\wwwroot\test-site
        ip: "*"
        port: 80
        hostname: "test-site.xyz"  


   

